# Generated by Django 4.2.1 on 2023-05-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_remove_topics_blogs'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='topic.topics'),
        ),
    ]
