# Generated by Django 4.2.1 on 2023-05-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic1', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['blogName']},
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic1.topics'),
        ),
    ]
