# Generated by Django 4.2.1 on 2023-05-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_topics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
