# Generated by Django 4.2.1 on 2023-05-14 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_interest_person_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='interests',
            new_name='interest',
        ),
    ]
