# Generated by Django 4.2.1 on 2023-05-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50)),
                ('TopicName', models.CharField(max_length=200)),
                ('DateOfPublish', models.DateField(auto_now=True)),
                ('Contact', models.CharField(max_length=14)),
            ],
        ),
    ]
